create table if not exists {}(
   id          TEXT   COMMENT       '工作项id',
   name        TEXT   COMMENT       '工作项名称',
   pattern     TEXT   COMMENT       '工作项模式,分为节点模式(Node)/状态模式(State)',
   project_key TEXT   COMMENT       '空间id',
   simple_name TEXT   COMMENT       '空间域名',
   state_times TEXT   COMMENT       '节点时间',
   template_id TEXT   COMMENT       '使用的模板id',
   sub_stage   TEXT   COMMENT       '需求状态(仅需求有值)',
   template_type TEXT COMMENT       '模板类型',
   updated_at TEXT    COMMENT       '更新时间 毫秒时间戳',
   updated_by TEXT    COMMENT       '更新者userKey',
   work_item_status   TEXT COMMENT  '工作项状态(除需求外有值)',
   work_item_type_key TEXT COMMENT  '工作项类型',
   created_at TEXT     COMMENT      '创建时间 毫秒时间戳',
   created_by TEXT     COMMENT      '创建者userKey',
   current_nodes TEXT  COMMENT      '当前进行中节点(仅节点流有值)',
   deleted_by TEXT     COMMENT      '删除人user_key',
   deleted_at TEXT     COMMENT      '删除时间戳，毫秒精度',
   qa_validate_schedule TEXT COMMENT 'QA验收',
   field_key  TEXT     COMMENT      'key',
   field_type_key TEXT COMMENT      'key_type',
   label TEXT ,
   `value` TEXT,
   type_name TEXT comment '类型名称'
)